### ISSUE TITLE
Turbo 7.3 Update Bug

### ISSUE THREAD

**Issue by jonsgreen** [hotwired/turbo#893] opened 2023-03-08 11:31 UTC
I recently update to Turbo 7.3 and found that some links I am adding to the page are suddenly returning the full page html when clicked even though they have the data-turbo-frame attribute set on them. I am trying to just update a modal which does in fact get updated but the page underneath the modal suddenly becomes blank. This works perfectly on Turbo 7.2. 

I will note that no Turbo-Frame header is being sent in the network request on Turbo 7.3 but it is on Turbo 7.2.

This might be something that is hard to reproduce but I am suspecting it has something to do with how these links are being added to the page. They are added after a turbo_stream request updates a div on the page within the turbo-frame. Again, this works perfectly if I switch back to Turbo 7.2 and there are no console errors being reported. 

I can try to recreate the issue in a test example but thought I would first report it to see if this is a known issue or something obvious might be going so that I am not spinning my wheels trying to distill it. 

Thanks for your time and consideration and please let me know how I can help.

**Comment by kevinmcconnell** [comment] 2023-03-08 11:42
Hi @jonsgreen. This isn't a known issue as far as I'm aware. Thanks for reporting it.

To make sure I'm following, is this the sequence of events that you're seeing:

- A turbo stream response updates a div which is inside a `<turbo-frame>`, and that response includes links.
- When those links are clicked, Turbo is not sending the expected `Turbo-Frame` header with the request.
- And when the response is returned, content outside of the frame is being updated.

If you are able to recreate the issue in a test example, that would be great. That should help us investigate what's going on.

**Comment by jonsgreen** [comment] 2023-03-09 04:01
@kevinmcconnell so far I cannot create a minimal reproduction of the bug. I definitely have the problem on my app but the pattern works fine with a vanilla rails app. For a moment I thought maybe it could have something to do with the fact that the turbo stream request is happening from a stimulus controller using request.js but I tried to do the same thing in the minimal example and the added links still worked fine requesting turbo frames with the Turbo-Frame header passed along. 

I might play with it some more to see if I can figure out anything else but otherwise we may just want to close this issue. Perhaps someone else will have a similar problem and we can triangulate.

**Comment by jonsgreen** [comment] 2023-03-09 05:05
@kevinmcconnell I have one more little clue that might be helpful. I just realized that not only is the link request not requesting a Turbo-Frame, it ends up changing the url on the page. I don't really know much about debugging javascript in the browser but the request follows the following chain gotten from the network initiator in Chrome (I believe it is in reverse order): 


  | perform | @ | application-49895f6….js:11157
-- | -- | -- | --
  | await in perform (async) |   |  
  | issueRequest | @ | application-49895f6….js:12389
  | visitStarted | @ | application-49895f6….js:12634
  | start | @ | application-49895f6….js:12345
  | startVisit | @ | application-49895f6….js:12902
  | visitProposedToLocation | @ | application-49895f6….js:12629
  | visitProposedToLocation | @ | application-49895f6….js:13590
  | proposeVisit | @ | application-49895f6….js:12893
  | visit | @ | application-49895f6….js:13530
  | followedLinkToLocation | @ | application-49895f6….js:13583
  | LinkClickObserver.clickBubbled | @ | application-49895f6….js:11758


Meanwhile successful turbo-frame request have the following: 



  | perform | @ | application-49895f6….js:11157
-- | -- | -- | --
  | await in perform (async) |   |  
  | (anonymous) | @ | application-49895f6….js:14117
  | visit | @ | application-49895f6….js:14110
  | loadSourceURL | @ | application-49895f6….js:13961
  | sourceURLChanged | @ | application-49895f6….js:13934
  | attributeChangedCallback | @ | application-49895f6….js:10793
  | set src | @ | application-49895f6….js:10803
  | (anonymous) | @ | application-49895f6….js:14124
  | withCurrentNavigationElement | @ | application-49895f6….js:14296
  | navigateFrame | @ | application-49895f6….js:14123
  | linkClickIntercepted | @ | application-49895f6….js:14003
  | LinkInterceptor.linkClicked | @ | application-49895f6….js:11717
  | dispatch | @ | application-49895f6….js:10985
  | notifyApplicationAfterClickingLinkToLocation | @ | application-49895f6….js:13670
  | applicationAllowsFollowingLinkToLocation | @ | application-49895f6….js:13662
  | willFollowLinkToLocation | @ | application-49895f6….js:13578
  | LinkClickObserver.clickBubbled | @ | application-49895f6….js:11756

It seems like there is a deviation right in the beginning where it ends up calling `followedLinkToLocation`. 

I don't know anything about this lower level code but perhaps it would suggest something to someone who is more familiar?

**Comment by jonsgreen** [comment] 2023-03-09 06:35
I finally figured out the difference that is causing the problem. The links that are added are inside a custom autocomplete component that is backed by a stimulus controller. I have a `click@window` for closing the autocomplete results (which contains the links). If I remove that click handler then everything works fine. Somehow this seems to make the event.defaultPrevented set to true and interferes with the whole turbo frame flow. 

Note again that this only started happening on Turbo 7.3.

**Comment by kevinmcconnell** [comment] 2023-03-09 09:59
@jonsgreen that's helpful, thanks. Can I ask what version you were using before that worked? Also how is your Stimulus controller interacting with the event -- is it calling `event.preventDefault()` or is there more to it?

**Comment by jonsgreen** [comment] 2023-03-09 14:02
There is no `event.preventDefault()` in the Stimulus controller. 

Everything worked fine on Turbo 7.2.0

Now that I better understand the issue I will see if I can reproduce it in the minimal example I started. The whole turbo-stream was a red herring in the end.

**Comment by jonsgreen** [comment] 2023-03-09 14:21
@kevinmcconnell So I was just able to determine the bigger source of the issue. While the stimulus controller does not call `event.preventDefault` it does set the innerHTML to '' which effectively removes the link from the page. I am not sure that Turbo should be responsible for dealing with that kind of twisted behavior so I would be fine if you close this issue. I can hopefully find a different way to deal with the situation. If you disagree then you can let me know. 

Thanks so much for your incredibly prompt responses to my seemingly spurious issue.

**Comment by kevinmcconnell** [comment] 2023-03-09 14:33
@jonsgreen ah interesting! Glad to hear there was an explanation. It's curious that it worked differently with the previous Turbo version, but it does sound like an unusual edge case. I wonder if changing that controller to call `event.preventDefault()` would help then, if the intended behaviour is for your Stimulus controller to hijack the click completely? There are also the [`turbo:*` events](https://turbo.hotwired.dev/reference/events) that may be useful if you want it to intercept the clicks in some other way.

I'll close this issue then, if you're happy that this is an application issue. But feel free to reach out if it does turn out to be something unexpected on the Turbo side after all!

**Closed by kevinmcconnell** 2023-03-09 14:33 UTC
