### ISSUE TITLE
`[data-turbo-cache=false]` and browser’s `Back` or `Forward` buttons

### ISSUE THREAD

**Issue by seb-jean** [hotwired/turbo#710] opened 2022-09-10 15:08 UTC
Hi,

I put `data-turbo-cache="false"` on element.
I clicked on a link on the site.
I went back with the browser's `Back` button. But element with `data-turbo-cache="false"` has been removed from the DOM.

Is it normal ? Is it a bug?
Thanks

**Comment by seanpdoyle** [comment] 2022-09-10 15:15
Thank you for opening this issue. Could this behavior have been fixed by https://github.com/hotwired/turbo/pull/674? It has been merged into `main` but isn't yet part of a release.

**Comment by seb-jean** [comment] 2022-09-10 15:36
I had tried this solution #674  but it didn't work. The behavior is the same.

**Comment by seb-jean** [comment] 2022-09-11 15:32
With examples.

So I clicked on "Page 2".
I arrived on Page 2.
I went back with the browser's `Back` button and `<section>` has been removed from the DOM

```html
<!-- page1.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Turbo</title>
    <script type="module">
        import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo@next';
    </script>
</head>
<body>
    <section data-turbo-cache="false">
        <p><a href="page2.html">Page 2</a></p>
    </section>
</body>
</html>
```

```html
<!-- page2.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Turbo</title>
    <script type="module">
        import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo@next';
    </script>
</head>
<body>
    <h1>Page2</h1>
</body>
</html>
```

**Comment by seanpdoyle** [comment] 2022-09-11 15:56
The more I think about this, the more I think it's working as intended.

What is the expected behavior in this situation? What is the intent behind marking an element `[data-turbo-cache="false"]`?

**Comment by seb-jean** [comment] 2022-09-11 16:15
**Expected behavior in this situation:**
In `page1.html`, `<section>` should not be removed from the DOM when I went back with the browser's `Back` button:
```html
<section data-turbo-cache="false">
    <p><a href="page2.html">Page 2</a></p>
</section>
```

**My intent behind marking an element [data-turbo-cache="false"]:**
Image I have a notification list like the Facebook page: https://www.facebook.com/notifications.

Unread notifications have a gray background. Read notifications have a white background.
I click on an unread notification and it updates its status to "read=true" (The link is /user?notification_id=123).

So this notification should be on a white background. I went back with the browser's `Back` button. And the background is always grey. When I refresh the page, the notification is on a white background.

That's why I would like to put `[data-turbo-cache="false"]`

**Comment by seanpdoyle** [comment] 2022-09-11 16:45
Navigating backward restores the contents from the Snapshot cache. Navigating forward with a `GET` request pushes a new Snapshot into the cache. Submitting a form with a destructive action (`POST`, `PUT`, etc) clears the cache of it contents.

As I understand the scenario you're describing, you're mutating the state of a record with a `GET` request (clicking an `<a>`), the _new_ page has the correct contents, and the old page that's present in the cache has out of date contents. Navigating back restores the old contents from the cache.

Marking an element with `[data-turbo-cache="false"]` isn't smart enough to decipher new content from old content. It's a directive that instructs the cache to ignore the element entirely, which is why it's removed from the cached contents. 

Have you considered replacing the `<a>` with a `<form>` with a destructive action so that the cached Snapshot doesn't become stale? Is there a way to update the cached Snapshot with new information [within a `turbo:before-cache` listener](https://turbo.hotwired.dev/handbook/building#understanding-caching)?

**Comment by seb-jean** [comment] 2022-09-11 18:18
You understood my scenario.

I can solve my problem with `<meta name="turbo-cache-control" content="no-cache">` on my whole site but I find it unfortunate.

**Comment by seb-jean** [comment] 2022-09-11 19:09
Another example is the number of unread notifications. This data is present in the header of the site so everywhere. As you can see in the GIF below, I have 99+ unread notifications. I click on "Notifications". All notifications become read and "99+" disappears. The problem is when I went back with the browser's Back button and "99+" appears for a few seconds then disappears. 

"99+" is loaded via `<turbo-frame class="empty:hidden inline-flex" id="..." src="..."></turbo-frame>`

![turbo](https://user-images.githubusercontent.com/12116264/189543532-574d29d7-d7ef-4bc1-865a-094612196d5d.gif)

This example does not use `[data-turbo-cache=false]`. 

When I use [data-turbo-cache=false] on the `<turbo-frame>`, at the time of navigating back, `<turbo-frame>` is removed from the DOM. This is the same behavior as the notification list example.

So I wonder if there is a way when we go back with the browser's `Back` button and without using [data-turbo-cache=false] to not to display "99+"

**Comment by tleish** [comment] 2022-09-13 14:28
Does `[data-turbo-permanent]` solve the "99+" issue?

see: [Persisting Elements Across Page Loads](https://turbo.hotwired.dev/handbook/building#persisting-elements-across-page-loads)

**Comment by seb-jean** [comment] 2022-09-13 14:49
I tried `[data-turbo-permanent]` on `<turbo-frame>`.

When I click "Notifications", the "99+" badge should update (it should disappear) but it doesn't:

![turbo](https://user-images.githubusercontent.com/12116264/189931713-30da54e6-032a-4d34-af3f-354f2aac00ab.gif)


```html
<!-- My HTML code without CSS classes -->
<div>
   <ul>
      <li>
         <a href="/notifications">
            <span aria-hidden="true"></span>
            <div>
               <span>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                     <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"/>
                  </svg>
                  <turbo-frame id="notifications-top-bar-unseen-count" src="/notifications/count" data-turbo-permanent></turbo-frame>
               </span>
            </div>
            <div>Notifications</div>
         </a>
      </li>
   </ul>
</div>
```

```html
<!-- My HTML code with CSS classes -->
<div class="hidden md:space-x-2 md:flex lg:w-auto w-full">
   <ul class="grid grid-cols-5 gap-x-6 lg:w-auto w-full">
      <li class="border-transparent inline-flex border-b-[3px] items-center relative justify-center pt-[3px] text-center">
         <a href="/notifications" class="group px-1 text-gray-500 hover:text-gray-700">
            <span class="absolute inset-0" aria-hidden="true"></span>
            <div class="flex justify-center">
               <span class="relative inline-block">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true"  class="h-6 w-6 stroke-gray-400 group-hover:stroke-gray-500">
                     <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"/>
                  </svg>
                  <turbo-frame class="empty:hidden inline-flex items-center justify-center rounded-full bg-red-500 px-1 text-2xs font-medium text-white min-w-4 absolute -top-1 ring-2 ring-white notifications-unseen-count" id="notifications-top-bar-unseen-count" src="/notifications/count" data-turbo-permanent></turbo-frame>
               </span>
            </div>
            <div class="font-medium text-xs mt-1.5 truncate">Notifications</div>
         </a>
      </li>
   </ul>
</div>
```

**Comment by tleish** [comment] 2022-09-13 15:01
- When clicking on "Notifications", is the page cached?
- Alternatively, would you want to change Notifications to a Non-GET (e.g. DELETE) instead of a GET since you are changing the state of the backend?  This would clear the cache without the need for `[data-turbo-permanent]`.

**Comment by seb-jean** [comment] 2022-09-13 15:25
> * When clicking on "Notifications", is the page cached?

The page is not cached.

> * Alternatively, would you want to change Notifications to a Non-GET (e.g. DELETE) instead of a GET since you are changing the state of the backend?  This would clear the cache without the need for `[data-turbo-permanent]`.

The Notifications page is a list of notifications so it would be strange to put DELETE.

**Comment by tleish** [comment] 2022-09-13 15:29
> The Notifications page is a list of notifications so it would be strange to put DELETE.

I understand, but clicking on the notifications "DELETES" the unread notifications status, meaning you mutate the backend state.  If it were my app, When there are unread notifications I would have the button send to a delete URL followed by a redirect to the list of notifications.  If there are no unread messages, I would have it go directly to the list of notifications.

One method is responsible for listing, the other is responsible for deleting unread status.  This would also clear the turbo-cache because non-GET request in the event of clearing unread notification status.

**Comment by mateuszbialowas** [comment] 2023-06-19 18:22
any updates?

**Comment by cjnahine090592** [comment] 2023-07-21 15:18
> You understood my scenario.
> 
> I can solve my problem with `<meta name="turbo-cache-control" content="no-cache">` on my whole site but I find it unfortunate.

Thanks Mate! I solved my issue

**Comment by lingfei1999** [comment] 2023-08-25 13:59
@seanpdoyle hi Sean, is it possible to implement something like this with turbo:
For element that wrapped in turbo-frame with src="/<url>", when we navigate using history, if there is turbo-frame with src, the framework will try to get fresh content, then render the whole page. So it can avoid the "flickering" or flash changes, but also leverage the cache with other part of the page which is ideal.

**Comment by johnmcdowall** [comment] 2024-03-04 02:52
@lingfei1999 did you ever figure this out?

**Closed** 2024-06-23 15:42 UTC
