### ISSUE TITLE
Shared Element Transitions API 

### ISSUE THREAD

**Issue by MSILycanthropy** [hotwired/turbo#585] opened 2022-05-12 18:56 UTC
With the advent of GoogleIO the [Shared Element Transition API](https://github.com/WICG/shared-element-transitions) has been exposed in Chrome Canary behind a couple flags. The power of this API, even in its infancy, can be seen [in this presentation](https://www.youtube.com/watch?v=JCJUPJ_zDQ4) and within [this demo](https://http203-playlist.netlify.app/videos/generating-your-color-palette-in-css/).  TLDR: it allows for transitions between content within SPAs with a couple lines of JS and some CSS. Similar to the way that content transitions on native iOS and Android apps.

Figured I'd toss the idea out there of the SET API being something Turbo leverages to allow for transitions with frames and streams. Not sure on how that implementation would look or any of the specifics, but I wanted to get the ball rolling on this discussion, since the API seems super sweet, even in the infantile state it's in right now. 

Not even sure if transitions between states of the DOM is something that has been on anyone's radar, it certainly wasn't on mine until after I saw this. Curious to see other people's thoughts on if this is something that could even work with Turbo in any capacity.

**Comment by domchristie** [comment] 2022-05-15 17:16
I created [Turn](https://github.com/domchristie/turn) to demonstrate navigation transitions with Turbo Drive. It doesn't transition position/size between screens, but it can provide some nice feedback when a user taps a link and can buy time on slower requests.

I have also experimented with the new Shared Element Transition API. I think it recommends that requests should finish first before transitioning, so you don't quite get the same benefits, but the transitions feel really nice.

Here's a demo (only works on Chrome Canary with the transition flag enabled): https://perfect-sparkling-condition.glitch.me/ and the source: https://perfect-sparkling-condition.glitch.me/script.js

**Comment by murb** [comment] 2023-03-08 15:36
There is now a W3C draft: [CSS View Transitions Module Level 1](https://drafts.csswg.org/css-view-transitions-1/) => seeing only Google-authors though...

**Comment by adrienpoly** [comment] 2023-03-08 17:08
This article provides good way to start using transition API with Turbo https://dev.to/nejremeslnici/how-to-use-view-transitions-in-hotwire-turbo-1kdi

I played quickly with drive but I think it isn't compatible by design with the cached preview. To prevent flickering effect your must disable the turbo cache

**Comment by domchristie** [comment] 2023-03-08 17:24
[Turn](https://github.com/domchristie/turn) supports the new view transition API in v1.4.0-2 and setting `Turn.config.experimental.viewTransitions = true`. Demo (Chrome only): https://charming-crumble-af45ba.netlify.app/

Ideally it'd be nice to be able to switch which type of transition to use based on a `data-*` attribute on the link. This won't be possible until something like: https://github.com/hotwired/turbo/pull/750 is merged.

**Closed** 2024-02-29 04:34 UTC
