### ISSUE TITLE
Hash is lost when redirecting after a form submission

### ISSUE THREAD

**Issue by stof** [hotwired/turbo#825] opened 2022-12-19 14:52 UTC
When a form submission redirects to a URL containing a hash, Turbo does not preserve that hash. This breaks the behavior of normal browser interactions where the target element would receive the focus (and be targetted with `:target()` in CSS). This mean that turbo Drive is not actually a drop-in enhancement.

Note: https://github.com/hotwired/turbo/pull/765 is adding tests reproducing the issue, but I haven't found any report for the issue yet.

**Comment by dhh** [comment] 2024-10-25 00:22
Indeed, dupe of #211

**Closed by dhh** 2024-10-25 00:22 UTC
