### ISSUE TITLE
Allowing usage of layout for turbo stream rendering

### ISSUE THREAD

**Issue by rodrigoruas** [hotwired/turbo#273] opened 2021-05-24 17:07 UTC
Hello,

It seems currently not possible to use layouts for **turbostream views rendering** and it may be a nice addition to deal with cases like flash updates.

Example: `application.turbo_stream.erb`

```ruby 
<turbo-stream action="append" target="flash">
  <template>
    <%= render partial: 'layouts/flash' %>
  </template>
</turbo-stream>
<%= yield %>
```

For **turbostream inline rendering** we are using the following approach:
 ```ruby 
def turbo_flash
    turbo_stream.append('flash', partial: 'layouts/flash')
 end
```

```ruby
render turbo_stream: turbo_flash + turbo_stream.update(.....)
          
```

As DHH suggested, we shouldn't do multiple inline turbostreams and we are looking for some better alternatives like the first example above.

Do you suggest a better way to deal with that? 

Thank you

**Comment by jduff** [comment] 2021-05-25 01:21
If you add  `layout -> { "application" if turbo_frame_request? }` to your application controller it should use the layout.

`turbo-rails` [disables the layout for turbo frame requests](https://github.com/hotwired/turbo-rails/blob/main/app/controllers/turbo/frames/frame_request.rb#L16). I wasn't able to find an explanation why, but it might be worth opening an issue asking there.

**Comment by rodrigoruas** [comment] 2021-05-25 09:55
hello @jduff! thanks for the message. I have opened an issue as you suggested. To make the layout works, I had to force like this:

```ruby 
respond_to do |format|
     format.turbo_stream do
       render layout: 'application'
     end
  end
```

**Comment by kassio** [comment] 2021-08-29 22:17
@rodrigoruas, I'm not sure @jduff was clear to you, but I think what he meant was: you can add the `layout -> { "application" if turbo_frame_request? } ` line to `ApplicationController` to avoid having to define the layout on each controller/action. I just tested it here and it worked. 😄

**Comment by brunoprietog** [comment] 2024-06-22 03:31
Hi @rodrigoruas, Turbo streams are intended to respond with concrete actions, rather than to render something so large that it can be within a layout.

If that's still what you're looking for, you can create a layout inside `app/views/layout/turbo_stream.html.erb`. You can use `yield` there, and be sure to use it where appropriate in your controller.

Closing this because it's not a bug. Feel free to ask questions in this thread and I'll be happy to help!

**Closed by brunoprietog** 2024-06-22 03:31 UTC
