### ISSUE TITLE
Duplicate content, Turbo stream added an already existing item

### ISSUE THREAD

**Issue by jankeesvw** [hotwired/turbo#132] opened 2021-01-24 19:17 UTC
I am currently working on an app that heavily leans on Hotwire (with Rails), I love working with it! Our apps feels so much more responsive because of Hotwire. 🚀 

There is one thing that I'm struggling with right now. Our app uses a lot of background jobs and sometimes the jobs are delayed for a couple of seconds.

This is our problem: Our app has a form where users create `Vehicles`. When the vehicle is created, I redirect the user back to the Vehicle#index. What sometimes happens, is that after the page is rendered by the server, the Turbo Stream job is picked up. Which sends the created vehicle to the user, even if the page already has that content. If that happens the user sees two identical vehicles (with the same `dom_id`'s), one rendered by the page render, and one added from the Turbo Stream.

It would help if Turbo would check if an `id` already existed, before blinding appending it to the target. Is that something you would be open to? If so, I would love to contribute to this project.

**Comment by danmcge** [comment] 2021-01-25 07:47
One solution to this (at least for now) is a Stimulus controller:

```js
// unique_controller.js

import { Controller } from "stimulus"

export default class extends Controller {
  connect() {
    if (this.alreadyInDom()) {
      this.element.remove()
    }
  }

  // Private

  alreadyInDom() {
    return document.querySelectorAll(`#${this.element.id}`).length > 1
  }
}
```

**Comment by dhh** [comment] 2021-01-25 09:13
Definitely want to deal with this. One suggestion that @sstephenson had presented was that Turbo would find all the id's in a turbo stream update, then remove all those elements from the DOM before adding what's in the action.

**Comment by jankeesvw** [comment] 2021-01-25 10:22
For now, I'm going to use a similar approach as suggested by @danmcge. That works, but you might see a flash of content when it's inserted and removed. The [HTML spec](https://www.w3.org/TR/html51/dom.html#the-id-attribute) says every ID should be unique in an HTML document so if you insert it twice it makes it invalid HTML.

@dhh the solution you mention sounds better, I would love to collaborate on this. I wonder how many people run into this issue, have you seen more reports of this? Adding this behavior could also make it a bit harder to understand, so it's definitely a noteworthy change to the library.

**Comment by dhh** [comment] 2021-01-25 10:45
I think spiking out the approach where we extract all the id's mention in an action template tag, then remove those from the dom before running the action, is the way to go.

**Comment by jankeesvw** [comment] 2021-01-25 10:58
Finding the element with the id's isn't hard. (`querySelectorAll("[id]")`). I looked at the source, is this where this change should happen?

https://github.com/hotwired/turbo/blob/f9d1651bee1fa1694b9812b34ca9177fe6345544/src/core/streams/stream_actions.ts#L4-L6

Shall I go ahead and create a PR for this? I have no real experience with TypeScript but with some help I can make this happen.

**Comment by tleish** [comment] 2021-01-26 13:48
While not good practice, it's not uncommon for duplicate IDs to show up in dynamic HTML.  Perhaps we could limit the scope to first degree children of template and target.  Something like:

```diff
export const StreamActions: { [action: string]: (this: StreamElement) => void } = {
  append() {
+   this.removeDuplicateTargetChildrenById();
    this.targetElement?.append(this.templateContent)
  },

  prepend() {
+   this.removeDuplicateTargetChildrenById();
    this.targetElement?.prepend(this.templateContent)
  },

+ removeDuplicateTargetChildrenById() {
+   const templateChildrenIds = [...this.templateContent.children].map(child => child.id).filter(Boolean);
+   [...this.targetElement?.children].forEach(targetChild => {
+       if(templateChildrenIds.includes(targetChild.id)){
+         targetChild.remove();
+       }
+   });
+ }

```

**Comment by jeromecornet** [comment] 2021-04-02 23:21
This solution seems to be the best approach to deal with duplicate content, and limiting the search for duplicates id only within the target seems the least risky approach.

:+1:

**Comment by jeromecornet** [comment] 2021-04-04 14:11
OK, I'm prepping a fix for this, but this regardless will break the tie between the action name (append/prepend) and the matching DOM functions so there are decisions to be made.

Here's a contrived example to highlight the possibilities:

Assuming the following
Target: 
```html
<ul id="vehicles">
  <li id="vehicle_1">Old car</li>
  <li id="vehicle_2">New car</li>
</ul>
```
Stream element:
```html
<turbo-stream action="append" target="vehicles">
  <template>
      <li id="vehicle_1">Old car with updates</li>
      <li id="vehicle_3">Newer car</li>
  </template>
</turbo-stream>
```

With the current code, the result is:
```html
<ul id="vehicles">
  <li id="vehicle_1">Old car</li>
  <li id="vehicle_2">New car</li>
  <li id="vehicle_1">Old car with updates</li>
  <li id="vehicle_3">Newer car</li>
</ul>
```
The duplicated id makes the html invalid (although it works), and append works like the DOM append function.

Would you change it to be:
**Option A:** do not append template children with id matching target children id
```html
<ul id="vehicles">
  <li id="vehicle_1">Old car</li>
  <li id="vehicle_2">New car</li>
  <li id="vehicle_3">Newer car</li>
</ul>
```

**Option B:** replace target children with the same id by template children, append the rest of the template (without the prior children)
```html
<ul id="vehicles">
  <li id="vehicle_1">Old car with updates</li>
  <li id="vehicle_2">New car</li>
  <li id="vehicle_3">Newer car</li>
</ul>
```

**Option C:** remove target children with the same id as template children id, append template like in https://github.com/hotwired/turbo/issues/132#issuecomment-767552026
```html
<ul id="vehicles">
  <li id="vehicle_2">New car</li>
  <li id="vehicle_1">Old car with updates</li>
  <li id="vehicle_3">Newer car</li>
</ul>
```

In the specific case we are trying to fix (duplicate append call with the same template containing one child), the 3 options will give the same result, but for more complicated scenarios we need to pick a behaviour.

We could also introduce another action type (maybe safe_append) if this breaks too much expectations of behaviour for append.

Any preference before I code this ? Sound like a few people in this thread have stated C), although this example may change that.

**Comment by jeromecornet** [comment] 2021-04-07 17:24
I wrote an implementation for the 3 options above
Option A: https://github.com/jeromecornet/turbo/pull/1
Option B: https://github.com/jeromecornet/turbo/pull/3
Option C: https://github.com/jeromecornet/turbo/pull/2

@seanpdoyle @tleish any opinion on the above ?

**Comment by tleish** [comment] 2021-04-07 20:56
### Don't append or prepend children with the same ID as existing ones
This doesn't seem like a good idea to me, as the content of the ID might have changed and the updated content would not be added.

### Remove target children with conflicting ID before adding template 
This may cause page content to jump around.  A developer might want to append or prepend an updated item at the beginning or end of a list, however considering this is mostly a race condition, I can't imagine the content to be that stale and not already at the beginning or ending of a list.

### Replace children with conflicting ID instead of append/prepend
I prefer this option over the other options.

I believe a cleaner version to my original code might be something like:

```javascript
append() {
  this.replaceDuplicateChildren()
  this.targetElement?.append(this.templateContent)
}

replaceDuplicateChildren() {
  this.duplicateChildren.forEach((elementChild, templateChild) => {
    elementChild.replaceWith(templateChild);
    templateChild.remove();
  })
}

get duplicateChildren() {
  return [...this.templateContent.children].map(templateChild => (
    [this.targetElement?.getElementById(templateChild.id), templateChild]
  )).filter((elementChild, templateChild) => elementChild);
}
```

**Comment by jeromecornet** [comment] 2021-04-12 14:08
@tleish agreed with your assessment.

I made some tweaks to your suggested code, and created a pull request https://github.com/hotwired/turbo/pull/239 (Option B) as a fix for this issue (and a better solution than https://github.com/hotwired/turbo-rails/pull/153)

**Comment by dhh** [comment] 2021-04-12 15:56
I think the jumping around is a feature not a bug. This would allow you to reorder things. If you need full control over the order of a list, you'll need to render the entire container instead. But as a basic default, I'd like to see option C. We remove any duplicates, then do as we're instructing.

In addition to that, we could introduce two new directives: update-or-append and update-or-prepend. Those would essentially do option B, but give you the control of whether to append or prepend on those that don't match an existing ID.

**Comment by jeromecornet** [comment] 2021-04-12 16:55
I don't have a strong opinion between B & C, because in practice I'm only trying to solve the double update problem (for which both solutions provide the same outcome) and I'd rather see an imperfect fix than nothing at all :-) 

If we were to introduce new methods, naming them will be hard. update-or-(ap|pre)pend is not great because `target` refers to the container, not the individual children, so the `update` part of the name is confusing (as the target isn't updated, its children possibly are) `update-children-or-append` is a mouthful but at least more descriptive.

I will update #239 to introduce those methods and we can debate its merit there, and create another PR for option C.

**Comment by tleish** [comment] 2021-04-12 17:56
@dhh -- thoughts on adding `duplicates` attribute for append/prepend?

```html
<turbo-stream action="append" target="list" duplicates="remove">
  <template>
    <li id="item_2">Item 2 (UPDATED)</li>
    <li id="item_3">Item 3 (UPDATED)</li>
  </template>
</turbo-stream>
```

Options for `duplicates` attribute might be:
- replace (default)
- remove
- ignore (maybe some want duplicates)

More Details: https://github.com/hotwired/turbo/pull/239#issuecomment-817901869

**Comment by dhh** [comment] 2021-04-12 18:12
Let’s just start with option C, yeah. I don’t see the point of having an option on what to do with duplicates because nothing except for replace seems desirable.

**Comment by jeromecornet** [comment] 2021-04-13 00:39
Option C is available at https://github.com/hotwired/turbo/pull/240

**Closed** 2021-06-08 08:54 UTC
