### ISSUE TITLE
Turbo Drive without the rest?

### ISSUE THREAD

**Issue by FredKSchott** [hotwired/turbo#369] opened 2021-09-02 06:36 UTC
Hey y’all! We’re looking into a turbo drive integration with Astro, and I was wondering if it was possible to only import drive without the rest?

I noticed that the new turbo is around 2x the size of Turbolinks. If we could get the side down by only importing the Drive functionality, that would be a big win.

**Comment by dhh** [comment] 2021-09-02 07:00
We don't have such an option at the moment. Most of it is pretty tightly integrated. But I wouldn't mind seeing some work go into this, particularly a tree-shaking path where we don't need actual separate packages.

**Comment by jeremy** [comment] 2021-11-24 22:24
Duplicate of #136

**Comment by wangchucheng** [comment] 2022-02-13 05:19
Seconded! It would be great if turbo has some tree-shaking structure so we can only import part (like turbo drive) of it.

**Closed** 2022-06-19 09:23 UTC
