### ISSUE TITLE
turbo:after-stream-render event

### ISSUE THREAD

**Issue by dwightwatson** [hotwired/turbo#408] opened 2021-09-26 05:18 UTC
We've got `turbo:before-stream-render` but it would also be helpful to have an event fire after the rendering has occurred as well.

My use-case is that the new DOM element is rendered into a scrollable window, so I'd like to scroll the new element into view after it's been rendered. It doesn't appear as though there is any event I can currently hook into that will let me perform this action after the DOM update has occurred.

**Comment by seanpdoyle** [comment] 2021-09-26 13:47
Is this a duplicate of https://github.com/hotwired/turbo/issues/92 and https://discuss.hotwired.dev/t/event-to-know-a-turbo-stream-has-been-rendered/1554/6?

**Comment by dwightwatson** [comment] 2021-09-26 18:18
Apologies, I did search but nothing came up.

**Closed** 2021-09-26 22:01 UTC

**Comment by woto** [comment] 2022-07-16 18:33
It helped me https://github.com/hotwired/turbo/pull/20#issue-773325276. Didn't found any drawbacks yet.
