### ISSUE TITLE
can only interact with a turbo frame once?

### ISSUE THREAD

**Issue by gingerlime** [hotwired/turbo#249] opened 2021-04-17 07:28 UTC
It's probably something silly, but I couldn't figure it out yet...

The problem: **After interacting with a specific turboframe, I cannot interact with it again**.

First off: **the server response does contain the correct turbo-frame-id** :)

Further details:

I have a simple form to inline edit the title of an item. It works on all items on the list perfectly. I click edit, update, click save, and the change is reflected. However if I try to do this another time on the same item, it just doesn't do anything. No errors. If I edit another untouched item, it works fine.

When I inspect the element after updating, it still has the turbo-frame-id provided in the responses, but somehow also added `src` which wasn't returned by the server... I'm not sure if this is a potential clue?

See attached video that hope demonstrates this?

![CleanShot 2021-04-17 at 09 07 32](https://user-images.githubusercontent.com/524274/115105153-5ca4a100-9f5d-11eb-9f03-a725a446d44c.gif)

using: turbo-rails gem 0.5.9, turbo-rails 7.0.0-beta.5, rails 6.0 with webpacker 5.2.1

**Comment by gingerlime** [comment] 2021-04-17 07:47
Update: I tried to manually remove the `src` attribute from the turbo-frame with the inspector, and it then lets me interact with it... I'm not sure what's injecting the `src`, because the server does not return it...

**Comment by JonathanLorimer** [comment] 2021-04-20 04:02
I am having this same issue, are `turbo-frame`'s only meant to be executed once?

**Comment by JonathanLorimer** [comment] 2021-04-20 04:42
I am not sure if this is helpful, but I noticed that on the initial load the `src` path uses whatever you set it as in your html, but on the second request the `src` is set with the full domain. It is after this second request (first click) that the `turbo-frame` stops working. Perhaps setting the `src` to the full path is causing issues? Just speculating.

Initial Load
![1618893599_grim](https://user-images.githubusercontent.com/32466011/115338644-3eaf8a00-a171-11eb-8575-fd2f95c7e896.png)

After first click
![1618893612_grim](https://user-images.githubusercontent.com/32466011/115338667-4ec76980-a171-11eb-8db9-c022528ba072.png)

**Comment by aroemers** [comment] 2021-04-21 20:54
Related/duplicate of #245?

**Comment by JonathanLorimer** [comment] 2021-04-21 21:01
@aroemers perhaps, I guess the bigger question is whether or not you are supposed to be able to execute a request within a turbo frame more than once? In my case I am trying to return a random word on every request so the result changes, does turbo assume that links are idempotent and therefore doesn't execute another request as an optimization?

**Comment by martinschnurer** [comment] 2021-04-28 19:49
I had similar issue and I solved it with the form url execution instead of <a href...> execution. Another a hrefs seem work just fine more than once. So I don't know where the problem is exactly

**Comment by martinschnurer** [comment] 2021-04-29 17:18
My problem was solved by downgrading to turbo@7.0.0-beta.4

**Comment by A7madXatab** [comment] 2021-04-29 23:57
I guess we're forced to to turbo_stream responses, i'm having the same issue, the only way i can see currently is removing `turbo-frame` tags and using `dom_id` to place ids on elements. and then send and respond with a stream that changes stuff. ¯\_(ツ)_/¯

**Comment by A7madXatab** [comment] 2021-04-30 06:50
well, i came up with this solution for now 

```js
import { Controller } from 'stimulus';

// there is a bug within turbo that dosent let you navigate
// from a frame more than once, to fix this you have to reset the frame
// src and all works. this is a monkey patch. to use it
// place it directly on a frame, data-controller="reset-frame-src"
// data-action="turbo:submit-end->reset-frame-src#reset"

export default class extends Controller {
    reset() {
        this.element.src = "";
    }
}import { Controller } from 'stimulus';

// there is a bug within turbo that dosent let you navigate
// from a frame more than once, to fix this you have to reset the frame
// src and all works. this is a monkey patch. to use it
// place it directly on a frame, data-controller="reset-frame-src"
// data-action="turbo:submit-end->reset-frame-src#reset"

export default class extends Controller {
    reset() {
        this.element.src = "";
    }
}
```

and i use it like so

```
turbo_frame_tag some-id,
                    data: {controller: 'reset-frame-src',
                           action: 'turbo:submit-end->reset-frame-src#reset'} 
```

this will reset the src only on form submits, and links will work as expected, for example clicking. a back button within the frame will work, but when a form submission completes, it resets the src.

**Comment by JonathanLorimer** [comment] 2021-04-30 14:14
I think this is the perpetrating [line of code](https://github.com/hotwired/turbo/blob/main/src/core/frames/frame_controller.ts#L80), specifically `this.sourceURL != this.currentURL`. But I am terrible at reading OO code, so someone else feel free to correct me.

**Comment by tleish** [comment] 2021-05-26 17:27
In our projects, only a few frames run into this issue.  For those frames, we use a stimulus controller.

Inspired by a [solution](https://github.com/hotwired/turbo/issues/249#issuecomment-829882126) from @A7madXatab , I created a `turbo-frame_controller.js` stimulus controller.

```javascript
import ApplicationController from './application_controller';

const ATTRIBUTE_NAMES = ['src', 'busy'];
const frameSrcUpdated = (event) =>
  event.type === 'attributes' && ATTRIBUTE_NAMES.indexOf(event.attributeName) > -1;

export default class extends ApplicationController {
  initialize() {
    this.observeMutations(this.dispatchEvents, this.element, { attributes: true });
  }

  dispatchEvents(events) {
    if (events.some(frameSrcUpdated)) {
      this.dispatchEvent();
    }
  }

  // dispatch fetch-start or before-render events
  dispatchEvent() {
    let eventName = 'before-render';
    if (this.element.hasAttribute('busy')) {
      eventName = 'fetch-start';
    }
    this.dispatch(eventName);
    this.dispatch(`${eventName}#${this.element.id}`);
  }

  // A bug within turbo prevents navigation from a frame more than once,
  // (see: https://github.com/hotwired/turbo/issues/249)
  // This temporary fix resets the frame src as a workaround
  // data-action="turbo:submit-end->turbo-frame#resetSrc"
  resetSrc() {
    this.element.src = '';
  }
}
```

Usage:

```html
<turbo-frame id="comments" data-controller="turbo-frame" data-action="turbo-frame:before-render->turbo-frame#resetSrc">
  ...
</turbo-frame>
```

Note: As a bonus this controller also provides `turbo-frame:fetch-start` and `turbo-frame:before-render` events to use with other functionality.

**Comment by philiplambok** [comment] 2021-06-06 06:42
Hmm, this seems a bug, but I think you can solve with this hack for now: https://github.com/hotwired/turbo/issues/245#issuecomment-847711320

**Closed** 2021-06-14 08:36 UTC

**Comment by shouichi** [comment] 2021-06-14 10:53
We had the same issue and #263 fixed the problem if the response status code is 302. However, it does not work if the response status code is 200. Is this behavior intentionaly?

**Comment by DustinArmstrong** [comment] 2021-06-19 05:30
@shouichi - Just came across this: [Turbo doesn’t allow regular rendering on 200](https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission)

Essentially, always `redirect_to`, don't `render` except when handling errors with:
```ruby
render :action, status: :unprocessable_entity
```

**Comment by shouichi** [comment] 2021-06-22 01:24
Thanks for the clarification 😺

**Comment by duleorlovic** [comment] 2021-07-16 19:42
The documentations says that POST should redirect, I'm not sure why GET should also use redirect ?
My use case is to use GET request for showing in another frame `<turbo-frame id='modal'></turbo-frame> <turbo-frame target="modal"><a href='posts/1/edit'>Edit</a></turbo-frame>`.
But OK, for now I'm using this hack to have redirection response
```
  def edit
      if params[:redirection_happens].blank?
        redirect_to edit_post_path(params[:id], redirection_happens: true)
      end
  end
```
