### ISSUE TITLE
broken: https://cdn.skypack.dev/@hotwired/turbo

### ISSUE THREAD

**Issue by mring33621** [hotwired/turbo#753] opened 2022-10-06 19:40 UTC
returns:

/*
 * [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;

**Comment by marcoroth** [comment] 2022-10-06 19:51
Hey @mring33621, sadly there is nothing we can do from our side. This is an issue on skypack's side. It seems like they are unresponsive in that matter.

As a workaround: You can either use it directly via `turbo-rails` (as you've discovered), install the package via npm directly or consider switching to another CDN for serving the js file.

```js
https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.2.0/dist/turbo.es2017-esm.js
https://ga.jspm.io/npm:@hotwired/turbo@7.2.0/dist/turbo.es2017-esm.js
```

Duplicate of: https://github.com/hotwired/turbo/issues/735 https://github.com/hotwired/turbo/issues/731 https://github.com/hotwired/turbo/issues/734

Related: https://github.com/skypackjs/skypack-cdn/issues/319

**Closed** 2022-12-25 02:34 UTC
