### ISSUE TITLE
Turbo Form Submission not triggered when submitting the Form via `Form.submit()`

### ISSUE THREAD

**Issue by JulianFeinauer** [hotwired/turbo#97] opened 2021-01-09 11:19 UTC
I want to trigger a (partial) Page update so my Idea was to use a Form which gets a Turbo-Stream `UPDATE` Response which will do the partial page update.

However, as I want to submit the Form via a different Element and not the Forms `<input type="submit"/>` I made a Stimulus Controller to handle the Form submition (e.g. on a button click).

However, if I do `form.submit()` from the Stimulus controller the Form submission is not intercepted by Turbo and is performed "regularly". Thus, I have to render an invisible `<input type="submit"/>` and trigger its `click()` method in Stimulus to make it work.

Is this a bug? Or just a conceptual thing?

**Comment by danjac** [comment] 2021-01-09 14:04
As a workaround you can use ` form.requestSubmit()`

**Comment by seanpdoyle** [comment] 2021-01-09 14:06
Closing as a duplicate of https://github.com/hotwired/turbo/issues/62 and https://github.com/hotwired/turbo/issues/33#issuecomment-750926503.

Turbo forms listen for [`submit` events](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent) fired during the `<form>` element submission lifecycle.

According to the MDN documentation, invoking [`HTMLFormElement.submit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) _does not_ fire these events:

> The HTMLFormElement.submit() method submits a given `<form>`.
> This method is similar, but not identical to, activating a form's submit <button>. When invoking this method directly, however:
>
> *   No submit event is raised. In particular, the form's onsubmit event handler is not run.
> *   Constraint validation is not triggered.
> The [`HTMLFormElement.requestSubmit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) method is identical to activating a form's submit `<button>` and does not have these differences.

The `HTMLFormElement.requestSubmit()` is [not yet supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit#Browser_compatibility), so you might want to install a [polyfill](https://github.com/javan/form-request-submit-polyfill).

**Closed by seanpdoyle** 2021-01-09 14:06 UTC
