### ISSUE TITLE
turbo-frame "_top" redirect to URLs containing '#' terminates URL at '#'

### ISSUE THREAD

**Issue by chrisgrande** [hotwired/turbo#565] opened 2022-04-09 07:13 UTC
I noticed this while working with Stripe checkout URLs, which are in the format of:

`https://checkout.stripe.com/pay/cs_test_a17h7hJ0yuLabPNRPjNhP6iKpyqkrEGhfQ7tk6Jma0QFC20ppupggSXGbr#fidkdWxOYHwnPyd1blpxYHZxWmJvQmBSTn1ncTxybWtsd2F0YWFmYTF%2FSjU1fzZDNFI0XGgnKSdjd2poVmB3c2B3Jz9xd3BgKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP3F3cGB4JSUl`

A hashtag appears about a third way thru all their URLs. → _gSXGbr_ **#** _fidkdW_

I reconfigured the form I'm submitting to use `date-turbo-frame="_top"` instead of `data-turbo="false"` so that I could replace the form using turbo streams on validation errors and do a full redirect to Stripe on success. I then noticed the successful redirect to Stripe stopped working — Stripe would load but just hang while trying to load the checkout page. This was caused by the Stripe URL that turbo was trying to redirect to being ended at where the hashtag appears in the URL.

**Comment by chrisgrande** [comment] 2022-04-14 00:35
I have crafted a demo showing the issue in action.

Both buttons hit the same endpoint `/redirect/` that returns a 303 redirect to an expired Stripe Checkout URL.

It is available here: https://turbo-redirect-test.onrender.com/

**Comment by dhh** [comment] 2022-06-18 18:33
Duplicate of https://github.com/hotwired/turbo/issues/211

**Closed by dhh** 2022-06-18 18:33 UTC
