### ISSUE TITLE
Make turbo progress bar optional

### ISSUE THREAD

**Issue by omarluq** [hotwired/turbo#1221] opened 2024-03-07 17:14 UTC
Adding Morph to Turbo has genuinely been a game changer—big thanks for all the effort in enhancing Turbo! While the Turbo progress bar's default setup during a refresh is understandable, having the flexibility to disable it, either across the board or per stream, could be really handy, e.g.

globally: 
```html
<meta name="turbo-refresh-method" content="morph"  progress-bar="none">
```
Or for specific streams:
```html
<turbo-stream action="refresh" progress-bar="none">
</turbo-stream>
```

**Comment by rbclark** [comment] 2024-03-07 21:27
Definitely agree, duplicate of https://github.com/hotwired/turbo/issues/1211

**Closed** 2024-03-07 21:43 UTC
